[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[client]
showErrorDetails = false
maxUploadSize = 200

[server]
maxUploadSize = 200
headless = true
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[ui]
hideTopBar = true
